name: Install Linux deps
description: Install build and runtime deps for Tauri app on Ubuntu
inputs:
  e2e:
    description: Include E2E desktop deps (webkit2gtk-driver, xvfb, gnome-keyring)
    required: false
    default: 'false'
  verify_glib:
    description: Run glib verification (dpkg, pkg-config checks)
    required: false
    default: 'true'
runs:
  using: composite
  steps:
    - name: Install Linux deps
      shell: bash
      run: |
        BASE_DEPS="build-essential pkg-config libglib2.0-dev libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libsecret-1-dev"
        E2E_DEPS="webkit2gtk-driver xvfb gnome-keyring gsettings-desktop-schemas dbus-x11 at-spi2-core libglib2.0-bin"
        sudo apt-get update
        if [ "${{ inputs.e2e }}" = "true" ]; then
          sudo apt-get install -y $BASE_DEPS $E2E_DEPS
          # Compile gsettings schemas to make them available
          sudo glib-compile-schemas /usr/share/glib-2.0/schemas/ || true
        else
          sudo apt-get install -y $BASE_DEPS
        fi

    - name: Verify glib installation
      if: ${{ inputs.verify_glib == 'true' }}
      shell: bash
      run: |
        echo "=== Verifying glib-2.0 installation ==="
        dpkg -l | grep libglib2.0-dev || echo "libglib2.0-dev not installed"
        find /usr -name 'glib-2.0.pc' 2>/dev/null || echo "glib-2.0.pc not found"
        pkg-config --modversion glib-2.0 || echo "pkg-config cannot find glib-2.0"
        pkg-config --exists 'glib-2.0 >= 2.70' && echo "glib-2.0 >= 2.70 found" || (echo "ERROR: glib-2.0 >= 2.70 not found"; exit 1)

    - name: Set PKG_CONFIG_PATH
      shell: bash
      run: echo "PKG_CONFIG_PATH=$(pkg-config --variable pc_path pkg-config)" >> $GITHUB_ENV
